version: '3.8'
services:
  app:
    build: ./fizzBuzz
    ports:
      - "9090:9090"
    environment:
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PORT=${PORT}
    depends_on:
      - redis
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

